variables:
  IMAGE_NAME: "mentour-biz"
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_RUN_OPTS: "-p 8888:8888 -v /var/www/mentour:/var/www/mentour"
  DEV_DOCKER_RUN_OPTS: "-p 8889:8889 -v /var/www/mentour:/var/www/mentour -e SPRING_PROFILES_ACTIVE=test"

include:
  - project: 'Mentour/ops/templates'
    file: '.build.yml'
  - project: 'Mentour/ops/templates'
    file: '.deploy.yml'