package uz.tune.mentourBiz.rest.domain.finance;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import uz.tune.mentourBiz.base.BaseEntity;
import uz.tune.mentourBiz.rest.domain.schoolManagement.school.School;
import uz.tune.mentourBiz.rest.domain.userManagement.user.User;
import uz.tune.mentourBiz.rest.enums.ExpenseEnums;
import uz.tune.mentourBiz.rest.enums.FinanceEnums;

import java.time.LocalDate;
import java.util.UUID;

/**
 * One outgoing payment from a school's own money — rent, utilities, a teacher's salary.
 *
 * <p>{@code finance_transactions} is the students' side of the ledger and every row there hangs off a
 * student; this is the other side, and nothing here belongs to a student. Keeping the two apart is what
 * lets "what did the school earn" and "what did the school spend" be answered without one query having
 * to know about the other.
 *
 * <p>Rows with {@code autoGenerated} set were written by another module rather than typed in — today
 * that means a teacher payment, which owns its expense row and is the only thing allowed to change it.
 * Editing or deleting one by hand would leave the two ledgers disagreeing about the same som.
 */
@Entity
@Table(name = "school_expenses")
@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
public class SchoolExpense extends BaseEntity {

    @Column(name = "uuid", unique = true, nullable = false)
    private UUID uuid = UUID.randomUUID();

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "school_id")
    private School school;

    @Column(name = "category")
    @Enumerated(EnumType.STRING)
    private ExpenseEnums.ExpenseCategory category = ExpenseEnums.ExpenseCategory.OTHER;

    // Always positive: the direction is the table, not the sign.
    @Column(name = "amount", nullable = false)
    private Long amount = 0L;

    @Column(name = "method")
    @Enumerated(EnumType.STRING)
    private FinanceEnums.PaymentMethod method;

    // The day the money left, which is not necessarily the day the row was created.
    @Column(name = "expense_date", nullable = false)
    private LocalDate expenseDate;

    // Headline in the expense list, e.g. "Office rent — August" or "Salary payment: Aziz Karimov".
    @Column(name = "title")
    private String title;

    @Column(name = "note", length = 1000)
    private String note;

    // True when another module created this row and owns it. See the class note.
    @Column(name = "auto_generated", nullable = false)
    private Boolean autoGenerated = Boolean.FALSE;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by_id")
    private User createdBy;

    // Soft-delete, as on FinanceTransaction: the row survives for audit and every total filters it out.
    @Column(name = "deleted", nullable = false)
    private Boolean deleted = Boolean.FALSE;
}
