package uz.tune.mentourBiz.rest.payload.res.finance;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uz.tune.mentourBiz.rest.enums.ExpenseEnums;
import uz.tune.mentourBiz.rest.enums.FinanceEnums;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/** One row of the expense list. */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ResSchoolExpense {

    private UUID uuid;
    private UUID schoolUuid;
    private ExpenseEnums.ExpenseCategory category;
    private Long amount;
    private FinanceEnums.PaymentMethod method;
    private LocalDate expenseDate;
    private String title;
    private String note;

    // True for rows payroll wrote itself. The UI greys out edit and delete on these — the teacher
    // payment they came from is what has to be reversed.
    private Boolean autoGenerated;

    private String createdByName;
    private Instant createdAt;
}
